import "./globals.css";
import { GamesProvider } from '../app/context/GamesContext';

export const metadata = {
  title: "KumStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body>
        <GamesProvider>
        {children}
        </GamesProvider>
      </body>
    </html>
  );
}
