import "./globals.css";
import { GamesProvider } from '../app/context/GamesContext';
import { AuthProvider } from "./context/AuthContext";

export const metadata = {
  title: "KumStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body>
        <AuthProvider>
          <GamesProvider>
          {children}
          </GamesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
